# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea667286e8b0a3ce3309e0f437ed533a075f0bfeabb27a5e78f1ac0ddc1fd361bb04ac2864c5f00b75ea18d47989ca34084ddb6e85759f6529440cee4fda176e

test:
  secret_key_base: f9869410181b5a7f13e53e151c8be034afb8b6fb28b78ab27aed589651bb5d40adab4e4c30d49dd03fbdea32b5d2ac20861ce28f11a1f59f41a528f37413dcee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
